### ISSUE TITLE
buildhub2 app failed to start on -stage env

### ISSUE THREAD

**Issue by bqbn** [mozilla/buildhub2#134]
Error shows

```
Jul 12 03:22:07 ip-172-31-27-217 systemd[1]: Started Daemon for buildhub2.
Jul 12 03:22:08 ip-172-31-27-217 docker-buildhub2[6141]: Not waiting for any services
Jul 12 03:22:08 ip-172-31-27-217 docker-buildhub2[6141]: python: can't open file 'gunicorn': [Errno 2] No such file or directory
```

gunicorn doesn't seem to be installed in the docker image.

```
$ sudo docker run -it --rm hub.prod.mozaws.net/pipelines/buildhub2/buildhub2 pip list |egrep -c gunicorn
0
```

**Comment by peterbe** [comment]
You're right! I guess that means I never test that in CI which is annoying. 
Perhaps there should be a step in the CircleCI that attempts to start the server and then we can curl that it's able to run production-like. 
For now, https://github.com/mozilla/buildhub2/pull/135 should suffice to move us forward.

**Comment by bqbn** [comment]
Tried it again, and unfortunately it failed with the same error.

```
Jul 19 00:39:28 ip-172-31-61-18.ec2.internal systemd[1]: Started Daemon for buildhub2.
Jul 19 00:39:29 ip-172-31-61-18.ec2.internal docker-buildhub2[3746]: Not waiting for any services
Jul 19 00:39:29 ip-172-31-61-18.ec2.internal docker-buildhub2[3746]: python: can't open file 'gunicorn': [Errno 2] No such file or directory
```

gunicorn is installed though, this time.

```
$ sudo docker run -it --rm hub.prod.mozaws.net/pipelines/buildhub2/buildhub2 pip list |egrep -c gunicorn
1
```

I'm thinking maybe this line https://github.com/mozilla/buildhub2/blob/master/bin/run.sh#L37 needs to use an absolute path to the gunicorn executable file.

**Comment by peterbe** [comment]
@bqbn I find that strange. First of all, I'm confident it's built:

```
docker-compose run --user 0 web bash
```
then
```
root@85b4fc6ecd71:/app# pip list | grep gunicorn
gunicorn              19.9.0
```

I suspect that that `hub.prod.mozaws.net/pipelines/buildhub2/buildhub2` was built before https://github.com/mozilla/buildhub2/pull/135

Ping me on IRC and we can debug this.

**Comment by bqbn** [comment]
@peterbe the image on -stage is correct (i.e. it is the one that's after https://github.com/mozilla/buildhub2/pull/135).

As it's said in https://github.com/mozilla/buildhub2/issues/134#issuecomment-406126125, 

> gunicorn is installed though, this time.


Here is an example I just ran using the image on -stage:

First, run the image and drop into the container,

```
$ sudo docker run -it --rm --net host -m 0b -e "PORT=8000"  --env-file /etc/dockerflow/buildhub2.txt  --log-driver=none          --name buildhub2   hub.prod.mozaws.net/pipelines/buildhub2/buildhub2:latest bash
Not waiting for any services
For high-speed test development, run: pip install pytest-watch
app@ip-172-31-61-18:~$
```

Then verify gunicorn is installed,

```
app@ip-172-31-61-18:~$ pip list |egrep gunicorn
gunicorn              19.9.0
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
app@ip-172-31-61-18:~$
```

Lastly, reproduce the error within the running container,

```
app@ip-172-31-61-18:~$ /app/bin/run.sh web
Not waiting for any services
python: can't open file 'gunicorn': [Errno 2] No such file or directory
```

I think [this line](https://github.com/mozilla/buildhub2/blob/master/bin/run.sh#L37) either

(a) needs to use an absolute path to the gunicorn executable file,

Or

(b) not use `${CMD_PREFIX_PYTHON:-python}` part, because gunicorn is located in $PATH. For example, here is what I see inside the container.

```
app@ip-172-31-61-18:~$ echo $PATH; which gunicorn
/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
/usr/local/bin/gunicorn
```

**Comment by peterbe** [comment]
Ah! Totally clear now. We don't need to execute `gunicorn` with `python`. It's its own program. I'll fix.

**Comment by peterbe** [comment]
Actually, let's reopen this to see if it worked.

**Comment by bqbn** [comment]
Good news is that `gunicorn` issue is gone. However (there is always a however, isn't it), there is a new startup error like below,

```
Aug 01 22:16:08 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: [2018-08-01 22:16:08 +0000] [6] [INFO] Starting gunicorn 19.9.0
Aug 01 22:16:08 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: [2018-08-01 22:16:08 +0000] [6] [INFO] Listening at: http://0.0.0.0:8000 (6)
Aug 01 22:16:08 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: [2018-08-01 22:16:08 +0000] [6] [INFO] Using worker: sync
Aug 01 22:16:08 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: [2018-08-01 22:16:08 +0000] [9] [INFO] Booting worker with pid: 9
Aug 01 22:16:08 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: [2018-08-01 22:16:08 +0000] [10] [INFO] Booting worker with pid: 10
Aug 01 22:16:08 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: [2018-08-01 22:16:08 +0000] [11] [INFO] Booting worker with pid: 11
Aug 01 22:16:08 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: [2018-08-01 22:16:08 +0000] [12] [INFO] Booting worker with pid: 12
Aug 01 22:16:08 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: [2018-08-01 22:16:08 +0000] [13] [INFO] Booting worker with pid: 13
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: [2018-08-01 22:16:10 +0000] [11] [ERROR] Exception in worker process
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: Traceback (most recent call last):
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: worker.init_process()
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: self.load_wsgi()
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: self.wsgi = self.app.wsgi()
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: self.callable = self.load()
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: return self.load_wsgiapp()
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: return util.import_app(self.app_uri)
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: __import__(module)
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/app/buildhub/wsgi.py", line 15, in <module>
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: from configurations.wsgi import get_wsgi_application
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/configurations/wsgi.py", line 14, in <module>
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: application = get_wsgi_application()
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: django.setup(set_prefix=False)
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 19, in setup
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: self._setup(name)
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: self._wrapped = Settings(settings_module)
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: mod = importlib.import_module(self.SETTINGS_MODULE)
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: return _bootstrap._gcd_import(name[level:], package, level)
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "<frozen importlib._bootstrap>", line 994, in _gcd_import
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "<frozen importlib._bootstrap>", line 971, in _find_and_load
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/configurations/importer.py", line 175, in load_module
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: reraise(err, "Couldn't setup configuration '{0}'".format(cls_path))
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/configurations/importer.py", line 159, in load_module
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: attributes = uppercase_attributes(obj).items()
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/configurations/utils.py", line 18, in uppercase_attributes
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: for name in filter(isuppercase, dir(obj)))
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/usr/local/lib/python3.6/site-packages/configurations/utils.py", line 18, in <genexpr>
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: for name in filter(isuppercase, dir(obj)))
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: File "/app/buildhub/settings.py", line 329, in DATABASES
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: DATABASES = super().DATABASES.value.copy()
Aug 01 22:16:10 ip-172-31-30-1.ec2.internal docker-buildhub2[2658]: AttributeError: Couldn't setup configuration 'buildhub.settings.Stage':  'dict' object has no attribute 'value'
```

**Comment by peterbe** [comment]
Once https://github.com/mozilla/buildhub2/pull/180 lands it should fix the problem. I was able to reproduce it locally by running `gunicorn` with the `DJANGO_CONFIGURATION=Stage`.

**Comment by peterbe** [comment]
There. Try now.

**Comment by bqbn** [comment]
Was able to start up the app this time. Closed for now.
